// <auto-generated />
namespace BusExp2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Algumas_Alteracoes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Algumas_Alteracoes));
        
        string IMigrationMetadata.Id
        {
            get { return "201907031256533_Algumas_Alteracoes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
